extends SceneTree
func _initialize() -> void:
	var progress = load("res://scripts/learning_progress.gd").new("user://learning-spec.json")
	progress.record("boat","touch","es",false)
	progress.record("come","touch","es",true)
	progress.record("wait","voice","en",false)
	progress.record("jump","voice","es",false)
	progress.record("bridge","typed","es",false)
	assert(progress.data.independent_choices == ["boat"],"Hints and speech are not independent touch-comprehension evidence")
	assert(progress.data.spoken_practice == 1 and progress.data.typed_practice == 1,"Typed, English and Spanish speech stay separate")
	assert(progress.write_save())
	var loaded = load("res://scripts/learning_progress.gd").new("user://learning-spec.json")
	loaded.read_save()
	assert(loaded.data == progress.data,"Evidence must survive a save round trip")
	var file := FileAccess.open("user://learning-spec.json",FileAccess.WRITE)
	file.store_string('{"version":1,"locale":"bad","used_intents":["boat","boat","fake"],"independent_choices":[17],"spoken_practice":-1}')
	file.close()
	loaded = load("res://scripts/learning_progress.gd").new("user://learning-spec.json")
	loaded.read_save()
	assert(loaded.data.locale=="en" and loaded.data.used_intents==["boat"] and loaded.data.spoken_practice==0)
	for suffix in ["",".bak",".tmp"]:
		DirAccess.remove_absolute(ProjectSettings.globalize_path("user://learning-spec.json"+suffix))
	print("[LearningProgressSpec] PASS: evidence separation, persistence and rejected invalid entries")
	quit()
